In [7]:
!pip install labelme tensorflow tensorflow-gpu opencv-python matplotlib albumentations

  Using cached labelme-5.1.1.tar.gz (1.5 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached tensorflow_gpu-2.10.1-cp39-cp39-win_amd64.whl (455.9 MB)
  Using cached opencv_python-4.7.0.68-cp37-abi3-win_amd64.whl (38.2 MB)
     ---------------------------------------- 7.2/7.2 MB 1.3 MB/s eta 0:00:00
  Using cached albumentations-1.3.0-py3-none-any.whl (123 kB)
  Using cached imgviz-1.6.2.tar.gz (7.7 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Using cached natsort-8.2.0-py3-none-any.whl (37 kB)
     ---------------------------------------- 2.5/2.5 MB 2.3 MB/s eta 0:00:00
     -------------------------------------- 151.6/151.6 kB 2.2 

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\is-os\\anaconda3\\envs\\tf-gpu\\Lib\\site-packages\\tensorflow\\lite\\experimental\\microfrontend\\python\\ops\\_audio_microfrontend_op.so'
Consider using the `--user` option or check the permissions.



In [8]:
import os
import uuid
import time
import cv2

In [3]:
imgs_path= os.path.join('data','images')
n_imgs=30

In [8]:
cam=cv2.VideoCapture(0)
for imgnum in range(n_imgs):
    print('collecting imgs {}'.format(imgnum))
    rtrn,frame=cam.read()
    imgname=os.path.join(imgs_path,f'{str(uuid.uuid1())}.jpg')
    cv2.imwrite(imgname,frame)
    cv2.imshow('picturefrm',frame)
    time.sleep(0.5)
    if cv2.waitKey(0) & 0xFF == ord('q'):
        break
cam.release()
cv2.destroyAllWindows()
        
    


collecting imgs 0
collecting imgs 1
collecting imgs 2
collecting imgs 3
collecting imgs 4
collecting imgs 5
collecting imgs 6
collecting imgs 7
collecting imgs 8
collecting imgs 9
collecting imgs 10
collecting imgs 11
collecting imgs 12
collecting imgs 13
collecting imgs 14
collecting imgs 15
collecting imgs 16
collecting imgs 17
collecting imgs 18
collecting imgs 19
collecting imgs 20
collecting imgs 21
collecting imgs 22
collecting imgs 23
collecting imgs 24
collecting imgs 25
collecting imgs 26
collecting imgs 27
collecting imgs 28
collecting imgs 29


In [9]:
!labelme

In [9]:
import tensorflow as tf
import json
import numpy as np
import matplotlib.pyplot as plt

In [10]:
#Limit GPU Memory Growth
gpus = tf.config.experimental.list_physical_devices('GPU')
for gpu in gpus: 
    tf.config.experimental.set_memory_growth(gpu, True)

RuntimeError: Physical devices cannot be modified after being initialized

In [6]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [7]:
tf.test.is_gpu_available()

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


True

In [16]:
tf.test.is_built_with_cuda

<function tensorflow.python.platform.test.is_built_with_cuda()>

In [17]:
pip install tensorflow-gpu

Note: you may need to restart the kernel to use updated packages.
  Using cached tensorflow_gpu-2.10.1-cp39-cp39-win_amd64.whl (455.9 MB)
     ---------------------------------------- 1.7/1.7 MB 770.7 kB/s eta 0:00:00
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
     ---------------------------------------- 5.9/5.9 MB 139.3 kB/s eta 0:00:00
     ------------------------------------ 438.7/438.7 kB 449.6 kB/s eta 0:00:00

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\is-os\\anaconda3\\Lib\\site-packages\\tensorflow\\compiler\\tf2tensorrt\\_pywrap_py_utils.pyd'
Consider using the `--user` option or check the permissions.




  Attempting uninstall: keras
    Found existing installation: keras 2.11.0
    Uninstalling keras-2.11.0:
      Successfully uninstalled keras-2.11.0
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.11.0
    Uninstalling tensorflow-estimator-2.11.0:
      Successfully uninstalled tensorflow-estimator-2.11.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.11.0
    Uninstalling tensorboard-2.11.0:
      Successfully uninstalled tensorboard-2.11.0


In [1]:
tf.test.is_gpu_available()

NameError: name 'tf' is not defined

In [8]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [15]:
images = tf.data.Dataset.list_files('data\\images\\*.jpg')

In [16]:
images.as_numpy_iterator().next()

b'data\\images\\ae93120a-8ea7-11ed-8f4c-9828a63d5a3b.jpg'

In [14]:
images.as_numpy_iterator().next()

b'data\\images\\00214b32-8ea7-11ed-aeb7-9828a63d5a3b.jpg'

In [11]:
def loadimg (x):
    byteimg=tf.io.read_file(x)
    img=tf.io.decode_jpeg(byteimg)
    return img

    

In [20]:
images=images.map(loadimg)

TypeError: in user code:

    C:\Users\is-os\AppData\Local\Temp\ipykernel_21220\4199762091.py:2 loadimg  *
        byteimg=tf.io.read_file(x)
    C:\Users\is-os\anaconda3\lib\site-packages\tensorflow\python\ops\io_ops.py:139 read_file  **
        return gen_io_ops.read_file(filename, name)
    C:\Users\is-os\anaconda3\lib\site-packages\tensorflow\python\ops\gen_io_ops.py:559 read_file
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    C:\Users\is-os\anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py:544 _apply_op_helper
        raise TypeError("%s expected type of %s." %

    TypeError: Input 'filename' of 'ReadFile' Op has type uint8 that does not match expected type of string.


In [21]:
images.as_numpy_iterator().next()

array([[[120, 106, 103],
        [121, 107, 104],
        [116, 105, 101],
        ...,
        [165, 176, 182],
        [163, 173, 182],
        [162, 175, 183]],

       [[118, 107, 105],
        [120, 109, 107],
        [120, 110, 108],
        ...,
        [166, 175, 182],
        [166, 176, 185],
        [165, 178, 186]],

       [[113, 104, 105],
        [114, 105, 106],
        [118, 113, 110],
        ...,
        [171, 180, 187],
        [170, 181, 187],
        [169, 180, 186]],

       ...,

       [[139, 153, 153],
        [137, 153, 152],
        [136, 152, 149],
        ...,
        [ 58,  62,  48],
        [ 53,  57,  43],
        [ 48,  52,  38]],

       [[138, 154, 153],
        [138, 154, 153],
        [137, 153, 150],
        ...,
        [ 56,  59,  48],
        [ 55,  58,  47],
        [ 54,  57,  46]],

       [[137, 153, 152],
        [138, 154, 153],
        [137, 156, 152],
        ...,
        [ 60,  63,  52],
        [ 56,  59,  48],
        [ 53,  56,  45]]

In [22]:
type(images)

tensorflow.python.data.ops.dataset_ops.MapDataset

In [23]:
img_gen = images.batch(4).as_numpy_iterator()

In [30]:
plotimg=img_gen.next()

In [ ]:
fig, ax = plt.subplots(ncols=4, figsize=(20,20))
for index, image in enumerate(plotimg):
    ax[index].imshow(image) 
plt.show()

In [34]:
for fldr in ['train','test','val']:
    for file in os.listdir(os.path.join('data', fldr, 'images')):
        
        filename = file.split('.')[0]+'.json'
        existing_filepath = os.path.join('data','labels', filename)
        if os.path.exists(existing_filepath): 
            new_filepath = os.path.join('data',fldr,'labels',filename)
            os.replace(existing_filepath, new_filepath)     


In [12]:
import albumentations as alb

In [13]:
augm = alb.Compose([alb.RandomCrop(width=450, height=450), 
                         alb.HorizontalFlip(p=0.5), 
                         alb.RandomBrightnessContrast(p=0.2),
                         alb.RandomGamma(p=0.2), 
                         alb.RGBShift(p=0.2), 
                         alb.VerticalFlip(p=0.5)], 
                       bbox_params=alb.BboxParams(format='albumentations', 
                                                  label_fields=['class_labels']))

In [39]:
img = cv2.imread(os.path.join('data','train', 'images','0ebde5c2-8ea7-11ed-a890-9828a63d5a3b.jpg'))

In [41]:
img.shape

(480, 640, 3)

In [43]:
with open(os.path.join('data', 'train', 'labels', '0ebde5c2-8ea7-11ed-a890-9828a63d5a3b.json'), 'r') as f:
    label = json.load(f)

In [59]:
label['shapes'][0]['points'][0][0]
label['shapes'][0]['points'][0][1]
label['shapes'][0]['points'][1][0]
label['shapes'][0]['points'][1][1]



485.06972019770467

In [89]:
coordinates=[0,0,0,0]
coordinates[0]=label['shapes'][0]['points'][0][0]
coordinates[1]=label['shapes'][0]['points'][0][1]
coordinates[2]=label['shapes'][0]['points'][1][0]
coordinates[3]=label['shapes'][0]['points'][1][1]


In [90]:
coordinates

[273.38164251207735, 145.31400966183574, 485.06972019770467, 479.0]

In [91]:
type(coordinates)

list

In [92]:
#pascal voc
coordinates=list(np.divide(coordinates,[640,480,640,480]))

In [93]:
coordinates

[0.4271588164251209,
 0.30273752012882443,
 0.7579214378089135,
 0.9979166666666667]

In [94]:
scaledimg=augm(image=img,bboxes=[coordinates],class_labels=['my face'])

In [98]:
scaledimg['bboxes'][0][:2]

(0.5119592055823942, 0.0)

In [82]:
scaledimg['image'].shape

(450, 450, 3)

In [85]:
scaledimg['class_labels']

['my face']

In [104]:
cv2.rectangle(scaledimg['image'],tuple(np.multiply(scaledimg['bboxes'][0][:2], [450,450]).astype(int)),
              tuple(np.multiply(scaledimg['bboxes'][0][2:], [450,450]).astype(int)),(0,255,0), 2)

array([[[ 23,  42,  67],
        [ 19,  38,  63],
        [ 20,  39,  64],
        ...,
        [146, 144, 150],
        [148, 146, 152],
        [147, 142, 149]],

       [[ 23,  44,  69],
        [ 17,  38,  63],
        [ 18,  39,  64],
        ...,
        [153, 148, 155],
        [155, 150, 157],
        [153, 148, 155]],

       [[ 17,  40,  65],
        [ 12,  35,  60],
        [ 12,  35,  60],
        ...,
        [159, 154, 161],
        [159, 154, 161],
        [162, 158, 163]],

       ...,

       [[143, 158, 176],
        [148, 161, 179],
        [144, 157, 175],
        ...,
        [195, 202, 221],
        [196, 203, 222],
        [195, 202, 221]],

       [[134, 151, 170],
        [141, 156, 175],
        [140, 155, 174],
        ...,
        [196, 201, 220],
        [195, 200, 219],
        [194, 199, 218]],

       [[131, 148, 167],
        [137, 152, 171],
        [138, 153, 172],
        ...,
        [193, 198, 217],
        [194, 199, 218],
        [194, 199, 218]]

In [ ]:
plt.imshow(scaledimg['image'])

In [106]:
for partition in ['train','test','val']: 
    for image in os.listdir(os.path.join('data', partition, 'images')):
        img = cv2.imread(os.path.join('data', partition, 'images', image))

        coords = [0,0,0.00001,0.00001]
        label_path = os.path.join('data', partition, 'labels', f'{image.split(".")[0]}.json')
        if os.path.exists(label_path):
            with open(label_path, 'r') as f:
                label = json.load(f)

            coords[0] = label['shapes'][0]['points'][0][0]
            coords[1] = label['shapes'][0]['points'][0][1]
            coords[2] = label['shapes'][0]['points'][1][0]
            coords[3] = label['shapes'][0]['points'][1][1]
            coords = list(np.divide(coords, [640,480,640,480]))

        try: 
            for x in range(60):
                scaledimg = augm(image=img, bboxes=[coords], class_labels=['my face'])
                cv2.imwrite(os.path.join('augmenteddata', partition, 'images', f'{image.split(".")[0]}.{x}.jpg'), scaledimg['image'])

                annotation = {}
                annotation['image'] = image

                if os.path.exists(label_path):
                    if len(scaledimg['bboxes']) == 0: 
                        annotation['bbox'] = [0,0,0,0]
                        annotation['class'] = 0 
                    else: 
                        annotation['bbox'] = scaledimg['bboxes'][0]
                        annotation['class'] = 1
                else: 
                    annotation['bbox'] = [0,0,0,0]
                    annotation['class'] = 0 


                with open(os.path.join('augmenteddata', partition, 'labels', f'{image.split(".")[0]}.{x}.json'), 'w') as f:
                    json.dump(annotation, f)

        except Exception as e:
            print(e)

In [15]:
#Load Augmented Images to Tensorflow Dataset
train_images = tf.data.Dataset.list_files('augmenteddata\\train\\images\\*.jpg', shuffle=False)
train_images = train_images.map(loadimg)
train_images = train_images.map(lambda x: tf.image.resize(x, (120,120)))
train_images = train_images.map(lambda x: x/255)

In [16]:
test_images = tf.data.Dataset.list_files('augmenteddata\\test\\images\\*.jpg', shuffle=False)
test_images = test_images.map(loadimg)
test_images = test_images.map(lambda x: tf.image.resize(x, (120,120)))
test_images = test_images.map(lambda x: x/255)

In [17]:
val_images = tf.data.Dataset.list_files('augmenteddata\\val\\images\\*.jpg', shuffle=False)
val_images = val_images.map(loadimg)
val_images = val_images.map(lambda x: tf.image.resize(x, (120,120)))
val_images = val_images.map(lambda x: x/255)

In [18]:
train_images.as_numpy_iterator().next()

array([[[0.20441176, 0.21911764, 0.2372549 ],
        [0.70594364, 0.72028184, 0.73860294],
        [0.7757966 , 0.7875613 , 0.80716914],
        ...,
        [0.18155637, 0.15067402, 0.02781863],
        [0.16507353, 0.14497548, 0.02634804],
        [0.17242648, 0.15980393, 0.06433824]],

       [[0.15245098, 0.17996323, 0.19270833],
        [0.39362746, 0.4122549 , 0.42843136],
        [0.7495098 , 0.7617647 , 0.78039217],
        ...,
        [0.16599265, 0.1463848 , 0.0278799 ],
        [0.20245098, 0.18198529, 0.06819853],
        [0.17077206, 0.14705883, 0.05      ]],

       [[0.18651961, 0.21789216, 0.22573529],
        [0.22052696, 0.2396446 , 0.25140932],
        [0.5448529 , 0.5487745 , 0.5644608 ],
        ...,
        [0.17340687, 0.15379901, 0.03915441],
        [0.18370098, 0.15723039, 0.04644608],
        [0.17536765, 0.14491421, 0.0504902 ]],

       ...,

       [[0.73762256, 0.7357843 , 0.7050858 ],
        [0.74172795, 0.72996324, 0.6946691 ],
        [0.736826  , 0

In [19]:
def load_labels(label_path):
    with open(label_path.numpy(), 'r', encoding = "utf-8") as f:
        label = json.load(f)
        
    return [label['class']], label['bbox']

In [20]:
train_labels = tf.data.Dataset.list_files('augmenteddata\\train\\labels\\*.json', shuffle=False)
train_labels = train_labels.map(lambda x: tf.py_function(load_labels, [x], [tf.uint8, tf.float16]))

In [21]:
test_labels = tf.data.Dataset.list_files('augmenteddata\\test\\labels\\*.json', shuffle=False)
test_labels = test_labels.map(lambda x: tf.py_function(load_labels, [x], [tf.uint8, tf.float16]))

In [22]:
val_labels = tf.data.Dataset.list_files('augmenteddata\\val\\labels\\*.json', shuffle=False)
val_labels = val_labels.map(lambda x: tf.py_function(load_labels, [x], [tf.uint8, tf.float16]))

In [23]:
len(train_images), len(train_labels), len(test_images), len(test_labels), len(val_images), len(val_labels)


(3780, 3780, 840, 840, 780, 780)

In [24]:
train = tf.data.Dataset.zip((train_images, train_labels))
train = train.shuffle(5000)
train = train.batch(8)
train = train.prefetch(4)

In [25]:
test = tf.data.Dataset.zip((test_images, test_labels))
test = test.shuffle(1300)
test = test.batch(8)
test = test.prefetch(4)

In [26]:
val = tf.data.Dataset.zip((val_images, val_labels))
val = val.shuffle(1000)
val = val.batch(8)
val = val.prefetch(4)

In [27]:
train.as_numpy_iterator().next()[1]


(array([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1]], dtype=uint8),
 array([[0.3638 , 0.2256 , 0.843  , 0.9634 ],
        [0.3044 , 0.02696, 0.821  , 0.7817 ],
        [0.08936, 0.3018 , 0.5874 , 1.     ],
        [0.     , 0.     , 0.2974 , 0.6777 ],
        [0.1517 , 0.2059 , 0.597  , 0.8853 ],
        [0.2019 , 0.     , 0.8716 , 0.662  ],
        [0.472  , 0.351  , 0.8994 , 0.9395 ],
        [0.1305 , 0.0869 , 0.4375 , 0.516  ]], dtype=float16))

In [28]:
data_samples = train.as_numpy_iterator()

In [29]:
result = data_samples.next()

In [ ]:
fig, ax = plt.subplots(ncols=4, figsize=(20,20))
for idx in range(4): 
    sample_image = result[0][idx]
    sample_coords = result[1][1][idx]
    
    cv2.rectangle(sample_image, 
                  tuple(np.multiply(sample_coords[:2], [120,120]).astype(int)),
                  tuple(np.multiply(sample_coords[2:], [120,120]).astype(int)), 
                        (255,0,0), 2)

    ax[idx].imshow(sample_image)

In [31]:
from tensorflow.keras.models import Model


In [2]:
from tensorflow.keras.layers import Input, Conv2D, Dense, GlobalMaxPooling2D
from tensorflow.keras.applications import VGG16

In [3]:
vgg = VGG16(include_top=False)

58892288/58889256 [==============================] - 22s 0us/step


In [35]:
vgg.summary()

Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, None, None, 3)]   0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, None, None, 64)    1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, None, None, 64)    36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, None, None, 64)    0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, None, None, 128)   73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, None, None, 128)   147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, None, None, 128)   0     

In [32]:
def build_model(): 
    input_layer = Input(shape=(120,120,3))
    
    vgg = VGG16(include_top=False)(input_layer)

    # Classification Model  
    f1 = GlobalMaxPooling2D()(vgg)
    class1 = Dense(2048, activation='relu')(f1)
    class2 = Dense(1, activation='sigmoid')(class1)
    
    # Bounding box model
    f2 = GlobalMaxPooling2D()(vgg)
    regress1 = Dense(2048, activation='relu')(f2)
    regress2 = Dense(4, activation='sigmoid')(regress1)
    
    facetracker = Model(inputs=input_layer, outputs=[class2, regress2])
    return facetracker

In [34]:
train.as_numpy_iterator().next()[1]

(array([[1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1],
        [1]], dtype=uint8),
 array([[0.4265  , 0.009224, 0.8076  , 0.545   ],
        [0.3704  , 0.2455  , 0.739   , 0.5825  ],
        [0.3066  , 0.368   , 0.7866  , 0.996   ],
        [0.261   , 0.342   , 0.688   , 0.9307  ],
        [0.846   , 0.      , 1.      , 0.628   ],
        [0.2344  , 0.657   , 0.521   , 1.      ],
        [0.3728  , 0.4543  , 0.885   , 1.      ],
        [0.229   , 0.936   , 0.756   , 1.      ]], dtype=float16))

In [36]:
facetracker = build_model()

In [37]:
facetracker.summary()


Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_2 (InputLayer)            [(None, 120, 120, 3) 0                                            
__________________________________________________________________________________________________
vgg16 (Functional)              (None, None, None, 5 14714688    input_2[0][0]                    
__________________________________________________________________________________________________
global_max_pooling2d (GlobalMax (None, 512)          0           vgg16[0][0]                      
__________________________________________________________________________________________________
global_max_pooling2d_1 (GlobalM (None, 512)          0           vgg16[0][0]                      
______________________________________________________________________________________________

In [38]:
X, y = train.as_numpy_iterator().next()


In [39]:
X.shape


(8, 120, 120, 3)

In [40]:
classes, coords = facetracker.predict(X)


In [41]:
classes, coords


(array([[0.42243853],
        [0.5236535 ],
        [0.51154715],
        [0.35114047],
        [0.34304678],
        [0.4234679 ],
        [0.43059266],
        [0.43777856]], dtype=float32),
 array([[0.40223572, 0.47771552, 0.29744253, 0.30058035],
        [0.3400945 , 0.52826947, 0.2844856 , 0.20036569],
        [0.3640592 , 0.51705766, 0.29359934, 0.26508322],
        [0.28196457, 0.5752365 , 0.31496382, 0.16609141],
        [0.24076569, 0.5775169 , 0.30741632, 0.22885868],
        [0.3488223 , 0.5458324 , 0.23812975, 0.1619801 ],
        [0.29621094, 0.5733281 , 0.34374413, 0.2281689 ],
        [0.36372262, 0.49054432, 0.31418535, 0.19771087]], dtype=float32))

In [43]:
len(train)

473

In [44]:
#Define Optimizer and LR
batches_per_epoch = len(train)
lr_decay = (1./0.75 -1)/batches_per_epoch


In [45]:
opt = tf.keras.optimizers.Adam(learning_rate=0.0001, decay=lr_decay)


In [46]:
def localization_loss(y_true, yhat):            
    delta_coord = tf.reduce_sum(tf.square(y_true[:,:2] - yhat[:,:2]))
                  
    h_true = y_true[:,3] - y_true[:,1] 
    w_true = y_true[:,2] - y_true[:,0] 

    h_pred = yhat[:,3] - yhat[:,1] 
    w_pred = yhat[:,2] - yhat[:,0] 
    
    delta_size = tf.reduce_sum(tf.square(w_true - w_pred) + tf.square(h_true-h_pred))
    
    return delta_coord + delta_size

In [47]:
classloss = tf.keras.losses.BinaryCrossentropy()
regressloss = localization_loss

In [48]:
#test loss metriccs

localization_loss(y[1], coords)


<tf.Tensor: shape=(), dtype=float32, numpy=11.428514>

In [49]:
classloss(y[0], classes)


<tf.Tensor: shape=(), dtype=float32, numpy=0.8529149>

In [50]:
regressloss(y[1], coords)


<tf.Tensor: shape=(), dtype=float32, numpy=11.428514>

In [51]:
lr_decay

0.0007047216349541929

In [52]:
#Train Neural Network
class FaceTracker(Model): 
    def __init__(self, eyetracker,  **kwargs): 
        super().__init__(**kwargs)
        self.model = eyetracker

    def compile(self, opt, classloss, localizationloss, **kwargs):
        super().compile(**kwargs)
        self.closs = classloss
        self.lloss = localizationloss
        self.opt = opt
    
    def train_step(self, batch, **kwargs): 
        
        X, y = batch
        
        with tf.GradientTape() as tape: 
            classes, coords = self.model(X, training=True)
            
            batch_classloss = self.closs(y[0], classes)
            batch_localizationloss = self.lloss(tf.cast(y[1], tf.float32), coords)
            
            total_loss = batch_localizationloss+0.5*batch_classloss
            
            grad = tape.gradient(total_loss, self.model.trainable_variables)
        
        opt.apply_gradients(zip(grad, self.model.trainable_variables))
        
        return {"total_loss":total_loss, "class_loss":batch_classloss, "regress_loss":batch_localizationloss}
    
    def test_step(self, batch, **kwargs): 
        X, y = batch
        
        classes, coords = self.model(X, training=False)
        
        batch_classloss = self.closs(y[0], classes)
        batch_localizationloss = self.lloss(tf.cast(y[1], tf.float32), coords)
        total_loss = batch_localizationloss+0.5*batch_classloss
        
        return {"total_loss":total_loss, "class_loss":batch_classloss, "regress_loss":batch_localizationloss}
        
    def call(self, X, **kwargs): 
        return self.model(X, **kwargs)

In [53]:
model = FaceTracker(facetracker)


In [54]:
model.compile(opt, classloss, regressloss)


In [56]:

logdir='logs'


In [57]:
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=logdir)


In [58]:
#traain
hist = model.fit(train, epochs=10, validation_data=val, callbacks=[tensorboard_callback])


Epoch 1/10
473/473 [==============================] - 118s 208ms/step - total_loss: 0.2860 - class_loss: 0.0432 - regress_loss: 0.2644 - val_total_loss: 0.0137 - val_class_loss: 9.7271e-05 - val_regress_loss: 0.0137
Epoch 2/10
473/473 [==============================] - 104s 205ms/step - total_loss: 0.0806 - class_loss: 0.0132 - regress_loss: 0.0740 - val_total_loss: 0.0124 - val_class_loss: 4.9175e-04 - val_regress_loss: 0.0122
Epoch 3/10
473/473 [==============================] - 107s 209ms/step - total_loss: 0.0292 - class_loss: 0.0027 - regress_loss: 0.0279 - val_total_loss: 0.0175 - val_class_loss: 2.0266e-05 - val_regress_loss: 0.0175
Epoch 4/10
473/473 [==============================] - 114s 222ms/step - total_loss: 0.0322 - class_loss: 0.0046 - regress_loss: 0.0299 - val_total_loss: 0.0222 - val_class_loss: 0.0080 - val_regress_loss: 0.0182
Epoch 5/10
473/473 [==============================] - 125s 231ms/step - total_loss: 0.0098 - class_loss: 1.8883e-04 - regress_loss: 0.0097 -

In [59]:
hist.history

{'total_loss': [0.045017022639513016,
  0.07236533612012863,
  0.014868070371448994,
  0.0036369068548083305,
  0.015382085926830769,
  0.0036335806362330914,
  0.003945093136280775,
  0.002674845978617668,
  0.002374919131398201,
  0.003945939242839813],
 'class_loss': [0.012128889560699463,
  0.00043221411760896444,
  0.00038213899824768305,
  2.984821912832558e-05,
  0.0001730743097141385,
  8.553358384233434e-06,
  0.0007136634667403996,
  9.685811164672486e-06,
  1.2457543562049977e-05,
  1.2427835827111267e-05],
 'regress_loss': [0.038952577859163284,
  0.07214923202991486,
  0.014677001163363457,
  0.003621982643380761,
  0.015295548364520073,
  0.003629304002970457,
  0.003588261315599084,
  0.0026700031012296677,
  0.0023686904460191727,
  0.003939725458621979],
 'val_total_loss': [0.013716837391257286,
  0.01242009922862053,
  0.017501819878816605,
  0.02224571630358696,
  0.0255100317299366,
  0.009848962537944317,
  0.0055332547053694725,
  0.00380179681815207,
  2.26467132

In [60]:
#Make Predictions on Test Set
test_data = test.as_numpy_iterator()


In [61]:
test_sample = test_data.next()


In [62]:
yhat = facetracker.predict(test_sample[0])

In [ ]:
fig, ax = plt.subplots(ncols=4, figsize=(20,20))
for idx in range(4): 
    sample_image = test_sample[0][idx]
    sample_coords = yhat[1][idx]
    
    if yhat[0][idx] > 0.9:
        cv2.rectangle(sample_image, 
                      tuple(np.multiply(sample_coords[:2], [120,120]).astype(int)),
                      tuple(np.multiply(sample_coords[2:], [120,120]).astype(int)), 
                            (255,0,0), 2)
    
    ax[idx].imshow(sample_image)

In [65]:
#saving
from tensorflow.keras.models import load_model
facetracker.save('facetracker.h5')


In [66]:
facetracker.save('facetracker.h5')


In [67]:
facetracker = load_model('facetracker.h5')


In [70]:
#real time detection
cam = cv2.VideoCapture(0)
while cam.isOpened():
    _ , frame = cam.read()
    frame = frame[50:500, 50:500,:]
    
    rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    resized = tf.image.resize(rgb, (120,120))
    
    yhat = facetracker.predict(np.expand_dims(resized/255,0))
    sample_coords = yhat[1][0]
    
    if yhat[0] > 0.5: 
        # Controls the main rectangle
        cv2.rectangle(frame, 
                      tuple(np.multiply(sample_coords[:2], [450,450]).astype(int)),
                      tuple(np.multiply(sample_coords[2:], [450,450]).astype(int)), 
                            (255,0,0), 2)
        # Controls the label rectangle
        cv2.rectangle(frame, 
                      tuple(np.add(np.multiply(sample_coords[:2], [450,450]).astype(int), 
                                    [0,-30])),
                      tuple(np.add(np.multiply(sample_coords[:2], [450,450]).astype(int),
                                    [80,0])), 
                            (255,0,0), -1)
        
        # Controls the text rendered
        cv2.putText(frame, 'my face', tuple(np.add(np.multiply(sample_coords[:2], [450,450]).astype(int),
                                               [0,-5])),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2, cv2.LINE_AA)
    
    cv2.imshow('EyeTrack', frame)
    
    if cv2.waitKey(0) & 0xFF == ord('q'):
        break
cam.release()
cv2.destroyAllWindows()

In [ ]:
from PIL import Image

# Open the image file
realimage = Image.open('Capture.PNG')

image_array = np.array(realimage)

plt.imshow(image_array)
plt.show()
